"""initial schema

Revision ID: e85d9b08cde7
Revises: 
Create Date: 2026-04-18 20:31:57.333627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e85d9b08cde7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('models_json', sa.Text(), nullable=False),
    sa.Column('conditions_json', sa.Text(), nullable=False),
    sa.Column('finding_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('findings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('model_short', sa.String(), nullable=False),
    sa.Column('probe', sa.String(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('prompt_preview', sa.String(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('adaptivity', sa.String(), nullable=False),
    sa.Column('interaction_mode', sa.String(), nullable=False),
    sa.Column('num_messages', sa.Integer(), nullable=False),
    sa.Column('num_target_calls', sa.Integer(), nullable=False),
    sa.Column('num_attacker_calls', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('target_tokens', sa.Integer(), nullable=False),
    sa.Column('attacker_tokens', sa.Integer(), nullable=False),
    sa.Column('detector_summary_json', sa.Text(), nullable=False),
    sa.Column('detail_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_findings_experiment', 'findings', ['experiment_id'], unique=False)
    op.create_index('ix_findings_model', 'findings', ['experiment_id', 'model'], unique=False)
    op.create_index('ix_findings_probe', 'findings', ['experiment_id', 'probe'], unique=False)
    op.create_table('scans',
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('model_short', sa.String(), nullable=False),
    sa.Column('probe', sa.String(), nullable=False),
    sa.Column('started_at', sa.String(), nullable=False),
    sa.Column('completed_at', sa.String(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('total_target_tokens', sa.Integer(), nullable=False),
    sa.Column('total_attacker_tokens', sa.Integer(), nullable=False),
    sa.Column('security_score_json', sa.Text(), nullable=False),
    sa.Column('compliance_assessment_json', sa.Text(), nullable=False),
    sa.Column('recommendations_json', sa.Text(), nullable=False),
    sa.Column('probe_results_summary_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scan_id')
    )
    op.create_index('ix_scans_experiment', 'scans', ['experiment_id'], unique=False)
    op.create_table('sessions',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index('ix_sessions_user', 'sessions', ['user_id'], unique=False)
    op.create_table('annotations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('finding_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_annotations_finding', 'annotations', ['finding_id'], unique=False)
    op.create_table('review_votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('finding_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finding_id', 'user_id', name='uq_review_votes_finding_user')
    )
    op.create_index('ix_review_votes_finding', 'review_votes', ['finding_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_review_votes_finding', table_name='review_votes')
    op.drop_table('review_votes')
    op.drop_index('ix_annotations_finding', table_name='annotations')
    op.drop_table('annotations')
    op.drop_index('ix_sessions_user', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_scans_experiment', table_name='scans')
    op.drop_table('scans')
    op.drop_index('ix_findings_probe', table_name='findings')
    op.drop_index('ix_findings_model', table_name='findings')
    op.drop_index('ix_findings_experiment', table_name='findings')
    op.drop_table('findings')
    op.drop_table('users')
    op.drop_table('experiments')
    # ### end Alembic commands ###
